/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddFactoryModal: typeof import('./src/components/AddFactoryModal.vue')['default']
    App: typeof import('./src/App.vue')['default']
    AppBar: typeof import('./src/components/AppBar.vue')['default']
    ErrorModal: typeof import('./src/components/ErrorModal.vue')['default']
    Factory: typeof import('./src/components/Factory.vue')['default']
    FactoryDrawer: typeof import('./src/components/FactoryDrawer.vue')['default']
    FactoryFloor: typeof import('./src/components/FactoryFloor.vue')['default']
    FactoryFloorsToolbar: typeof import('./src/components/FactoryFloorsToolbar.vue')['default']
    FactoryPanels: typeof import('./src/components/FactoryPanels.vue')['default']
    FactoryRow: typeof import('./src/components/FactoryRow.vue')['default']
    FloorEditModal: typeof import('./src/components/FloorEditModal.vue')['default']
    GettingStarted: typeof import('./src/components/GettingStarted.vue')['default']
    IconSelector: typeof import('./src/components/IconSelector.vue')['default']
    ThemeSwitcher: typeof import('./src/components/ThemeSwitcher.vue')['default']
    VAlert: typeof import('vuetify/components')['VAlert']
    VApp: typeof import('vuetify/components')['VApp']
    VAppBar: typeof import('vuetify/components')['VAppBar']
    VAppBarSubtitle: typeof import('vuetify/components')['VAppBarSubtitle']
    VAppBarTitle: typeof import('vuetify/components')['VAppBarTitle']
    VAutocomplete: typeof import('vuetify/components')['VAutocomplete']
    VBtn: typeof import('vuetify/components')['VBtn']
    VCard: typeof import('vuetify/components')['VCard']
    VCardActions: typeof import('vuetify/components')['VCardActions']
    VCardText: typeof import('vuetify/components')['VCardText']
    VCardTitle: typeof import('vuetify/components')['VCardTitle']
    VChip: typeof import('vuetify/components')['VChip']
    VCol: typeof import('vuetify/components')['VCol']
    VContainer: typeof import('vuetify/components')['VContainer']
    VDialog: typeof import('vuetify/components')['VDialog']
    VDivider: typeof import('vuetify/components')['VDivider']
    VExpansionPanel: typeof import('vuetify/components')['VExpansionPanel']
    VExpansionPanels: typeof import('vuetify/components')['VExpansionPanels']
    VExpansionPanelText: typeof import('vuetify/components')['VExpansionPanelText']
    VExpansionPanelTitle: typeof import('vuetify/components')['VExpansionPanelTitle']
    VFab: typeof import('vuetify/components')['VFab']
    VForm: typeof import('vuetify/components')['VForm']
    VIcon: typeof import('vuetify/components')['VIcon']
    VImg: typeof import('vuetify/components')['VImg']
    VList: typeof import('vuetify/components')['VList']
    VListItem: typeof import('vuetify/components')['VListItem']
    VListItemSubtitle: typeof import('vuetify/components')['VListItemSubtitle']
    VListItemTitle: typeof import('vuetify/components')['VListItemTitle']
    VMain: typeof import('vuetify/components')['VMain']
    VNavigationDrawer: typeof import('vuetify/components')['VNavigationDrawer']
    VRow: typeof import('vuetify/components')['VRow']
    VSpacer: typeof import('vuetify/components')['VSpacer']
    VTextarea: typeof import('vuetify/components')['VTextarea']
    VTextField: typeof import('vuetify/components')['VTextField']
  }
}
